# Generated by Django 2.2.10 on 2020-08-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveIntegerField(choices=[(4, 'ADMIN SOUS PREFECTORAL'), (3, 'ADMIN PREFECTORAL'), (2, 'VICE PRESIDENT'), (1, 'PRESIDENT')], primary_key=True, serialize=False),
        ),
    ]
