# Generated by Django 2.2.10 on 2020-08-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200822_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveIntegerField(choices=[(1, 'PRESIDENT'), (4, 'ADMIN SOUS PREFECTORAL'), (3, 'ADMIN PREFECTORAL'), (2, 'VICE PRESIDENT')], primary_key=True, serialize=False),
        ),
    ]
