# Generated by Django 2.2.10 on 2020-08-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200822_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveIntegerField(choices=[(1, 'PRESIDENT'), (2, 'VICE PRESIDENT'), (3, 'ADMIN PREFECTORAL'), (4, 'ADMIN SOUS PREFECTORAL')], primary_key=True, serialize=False),
        ),
    ]
