# Generated by Django 2.2.10 on 2020-08-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200824_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveIntegerField(choices=[(3, 'ADMIN PREFECTORAL'), (1, 'PRESIDENT'), (2, 'VICE PRESIDENT'), (4, 'ADMIN SOUS PREFECTORAL')], primary_key=True, serialize=False),
        ),
    ]
