# Generated by Django 2.2.10 on 2020-09-05 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import election.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('political_party', '0001_initial'),
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(choices=[('PRESIDENTIELLE', 'PRESIDENTIELLE'), ('LEGISLATIVE', 'LEGISLATIVE'), ('COMMUNALLE', 'COMMUNALLE')], default='PRESIDENTIELLE', max_length=80)),
            ],
            options={
                'db_table': 'election',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('adress', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.Locality')),
            ],
            options={
                'db_table': 'polling_station',
            },
        ),
        migrations.CreateModel(
            name='MinuteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_votes_obtained', models.IntegerField()),
                ('id_political_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_party.PoliticalParty')),
                ('id_polling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.PollingStation')),
            ],
            options={
                'db_table': 'minute_details',
            },
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_polling_planned', models.IntegerField(null=True, verbose_name='Nombre de bureau de vote')),
                ('nbr_polling_real', models.IntegerField(blank=True, null=True)),
                ('nbr_registrants', models.IntegerField(verbose_name="Nombre d'electeurs inscrits")),
                ('nbr_voters', models.IntegerField()),
                ('nbr_invalids_ballots', models.IntegerField(verbose_name='0')),
                ('nbr_votes_cast', models.IntegerField(verbose_name='Total des bulletins nuls')),
                ('image', models.ImageField(upload_to=election.models.get_pv_path, verbose_name='Photo du PV')),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
                ('polling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.PollingStation', verbose_name='Numero du bureau de vote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'minute',
            },
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
                ('political_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_party.PoliticalParty')),
            ],
            options={
                'db_table': 'election_candidate',
            },
        ),
    ]
