# Generated by Django 2.2.10 on 2020-09-27 16:47

from django.db import migrations, models
import election.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(choices=[('PRESIDENTIELLE', 'PRESIDENTIELLE'), ('LEGISLATIVE', 'LEGISLATIVE'), ('COMMUNALLE', 'COMMUNALLE')], default='PRESIDENTIELLE', max_length=80)),
            ],
            options={
                'db_table': 'election',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'election_candidate',
            },
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_registrants', models.IntegerField(blank=True, verbose_name="Nombre d'inscrits")),
                ('nbr_voters', models.IntegerField(verbose_name='Nombre de votants')),
                ('nbr_invalids_ballots', models.IntegerField(verbose_name='Bulletins nuls')),
                ('nbr_votes_cast', models.IntegerField(blank=True, verbose_name='Suffrage valablement exprimé')),
                ('nbr_votes_pro', models.IntegerField(default=0, verbose_name='Nombre de vote par procuration')),
                ('image', models.FileField(blank=True, upload_to=election.models.get_pv_path, verbose_name='Photo du PV')),
                ('incident', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to=election.models.get_incident_path, verbose_name="Photo de l'incident")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'minute',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MinuteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_votes_obtained', models.IntegerField(verbose_name='Votes obtenues')),
            ],
            options={
                'db_table': 'minute_details',
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('adress', models.CharField(default='', max_length=100)),
                ('nbr_registrants', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'polling_station',
            },
        ),
    ]
