# Generated by Django 2.2.10 on 2020-08-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('status', models.EmailField(max_length=254)),
                ('election_type', models.PositiveSmallIntegerField(choices=[(1, 'PRESIDENTIELLE'), (2, 'LEGISLATIVE'), (3, 'COMMUNALLE')])),
            ],
            options={
                'db_table': 'election',
            },
        ),
    ]
