# Generated by Django 2.2.10 on 2020-09-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
