# Generated by Django 2.2.10 on 2020-08-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20200822_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='status',
        ),
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
