# Generated by Django 2.2.10 on 2020-09-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20200905_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minute',
            name='nbr_polling_planned',
        ),
        migrations.RemoveField(
            model_name='minute',
            name='nbr_polling_real',
        ),
        migrations.AlterField(
            model_name='minute',
            name='nbr_invalids_ballots',
            field=models.IntegerField(verbose_name='Total des bulletins nuls'),
        ),
        migrations.AlterField(
            model_name='minute',
            name='nbr_registrants',
            field=models.IntegerField(verbose_name="Nombre d'inscrits"),
        ),
        migrations.AlterField(
            model_name='minute',
            name='nbr_voters',
            field=models.IntegerField(verbose_name='Nombre de votants'),
        ),
        migrations.AlterField(
            model_name='minute',
            name='nbr_votes_cast',
            field=models.IntegerField(verbose_name='Suffrage valablement exprimé'),
        ),
    ]
