# Generated by Django 2.2.10 on 2020-09-05 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20200905_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minute',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='minute',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election', verbose_name='Election'),
        ),
        migrations.AlterField(
            model_name='minute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Centralisateur'),
        ),
    ]
