# Generated by Django 2.2.10 on 2020-09-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20200905_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='image',
            field=models.ImageField(upload_to='pv', verbose_name='Photo du PV'),
        ),
    ]
