# Generated by Django 2.2.10 on 2020-09-05 20:55

from django.db import migrations, models
import election.models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_auto_20200905_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='minute',
            name='image',
            field=models.ImageField(upload_to=election.models.get_pv_path, verbose_name='Photo du PV'),
        ),
    ]
