# Generated by Django 2.2.10 on 2020-09-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_auto_20200905_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minute',
            old_name='image',
            new_name='image',
        ),
    ]
