# Generated by Django 2.2.10 on 2020-09-06 00:14

from django.db import migrations, models
import election.models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20200906_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='image',
            field=models.FileField(upload_to=election.models.get_pv_path, verbose_name='Photo du PV'),
        ),
    ]
