# Generated by Django 2.2.10 on 2020-09-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20200906_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutedetails',
            old_name='id_polling',
            new_name='polling',
        ),
    ]
