# Generated by Django 2.2.10 on 2020-09-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20200906_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingstation',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_station', to='locality.Locality'),
        ),
    ]
