# Generated by Django 2.2.10 on 2020-09-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_auto_20200908_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingstation',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.Locality'),
        ),
    ]
