# Generated by Django 2.2.10 on 2020-09-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_auto_20200908_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstation',
            name='numero',
            field=models.IntegerField(default=555),
            preserve_default=False,
        ),
    ]
